### ISSUE TITLE
Create Edit functionality

### ISSUE THREAD

**Issue by lumodon** [GuildCrafts/noob#73]
- Edit the start date for newbie's?
- Edit github handle (if changed after-the-fact)?
- Edit full name (got married while at guild?)
- Edit phone number?
- Edit email?
- Edit role? (They've been here for awhile and now are about to become a mentor?)

Should any user be able to edit their information in case of mistake? Should only admin's be able to edit information? (Would they be overwhelmed with minor correct requests?)

**Comment by punitrathore** [comment]
we only need edit functionality for the template tasks for now

**Comment by punitrathore** [comment]
this is done
